### ISSUE TITLE
Module causes Error when using Vite

### ISSUE THREAD

**Issue by anpari** [rubensworks/rdf-parse.js#56]
Hi Ruben!

First of all, thank you very much for your work! I really appreciate your contributions to the RDF eco-system!

I'm using `Vite` as my build tool and I'm having an issue with running a build with the `rdf-parse` module. Whenever I'm loading the served application in a browser, I'm getting the following error:

```
Uncaught TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at One (index-dd57c101.js:128:20209)
    at Z4 (index-dd57c101.js:128:21277)
    at tc (index-dd57c101.js:128:23249)
    at index-dd57c101.js:128:15488
```

pointing to this particular expression
```
Object.defineProperty(wd,"__esModule",{value:!0})
```

My `vite.config.ts` looks like this

```
import {defineConfig} from 'vite'
import vue from '@vitejs/plugin-vue'
import * as path from "path";
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill'

// https://vitejs.dev/config/
export default defineConfig({
    build: {
        target: "es2020",  // https://github.com/sveltejs/kit/issues/859
        commonjsOptions: {
            include: ['tailwind-config.cjs', 'node_modules/**'],
        },
    },
    optimizeDeps: {
        esbuildOptions: {
            target: "es2020",
            // Enable esbuild polyfill plugins https://stackoverflow.com/q/73954820
            plugins: [
                NodeModulesPolyfillPlugin()
            ]
        },
        include: ['tailwind-config'],
    },
    plugins: [vue()],
    assetsInclude: ['**/*.md'],
    resolve: {
        alias: {
             ...
        },
    },
})

``` 

I think that I'm encountering the same issue as [described here](https://stackoverflow.com/q/73954820).

Do you have an idea what this issue could be here?

**Comment by rubensworks** [comment]
This looks like the same problem as in https://github.com/comunica/comunica/issues/1128

A workaround is to put this in your Vite config:
```
{
  build: {
    commonjsOptions: {
      strictRequires: true
    }
  }
}

```

Ideally, this shouldn't be needed, but until we pinpoint what is causing the problem exactly, it's a good temporary workaround.
